# permissions for end users to edit externalresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalresource-editor-role
rules:
- apiGroups:
  - extension.kubeworkz.io
  resources:
  - externalresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.kubeworkz.io
  resources:
  - externalresources/status
  verbs:
  - get
