# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cluster.kubeworkz.io_clusters.yaml
- bases/tenant.kubeworkz.io_tenants.yaml
- bases/tenant.kubeworkz.io_projects.yaml
- bases/user.kubeworkz.io_users.yaml
- bases/user.kubeworkz.io_keys.yaml
- bases/quota.kubeworkz.io_kuberesourcequota.yaml
- bases/hotplug.kubeworkz.io_hotplugs.yaml
- bases/extension.kubeworkz.io_externalresources.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_clusters.yaml
#- patches/webhook_in_tenants.yaml
#- patches/webhook_in_projects.yaml
#- patches/webhook_in_users.yaml
#- patches/webhook_in_kuberesourcequota.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_clusters.yaml
#- patches/cainjection_in_tenants.yaml
#- patches/cainjection_in_projects.yaml
#- patches/cainjection_in_users.yaml
#- patches/cainjection_in_kuberesourcequota.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
